create table if not exists purchase
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product varchar(64)                          not null,
    price   double precision                     not null
);
