spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/test_db
    username: usr
    password: pwd

  sql:
    init:
      mode: always


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
